version: '4.0'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./datamysql:/docker-entrypoint-initbd.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
      image: postgres:latest
      ports:
        - '5432:5432'
      volumes:
        - ./datapstgr:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=pass

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: js-container
    ports:
      - '9999:9999'

